name = "gen_refs_fortran"
version = "0.1.0"
license = "Apache-2.0"

[[executable]]
name = "gen_refs_fortran"
source-dir = "."
main = "gen_refs_fortran.f90"

[dependencies]
s-dftd3 = { git = "https://github.com/dftd3/simple-dftd3", tag = "v1.6.0" }
