#!/usr/bin/env python3
# This file is part of tad-dftd3.
# SPDX-Identifier: Apache-2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
"""
Generate ``src/tad_dftd3/param/aliases.toml`` from s-dftd3's Fortran source.

s-dftd3 hardcodes functional-name aliasing (synonyms, hyphen-insensitivity) as a
``select case`` construct in ``get_method_id`` (``src/dftd3/param.f90``). That
aliasing is *not* present in the ``parameters.toml`` data asset that tad-dftd3
vendors as its damping-parameter source. Rather than hand-transcribing the
~180-arm switch-case into Python, this script derives the alias table
programmatically and writes it out as data, to be committed and re-generated
whenever upstream's aliasing changes.

Usage
-----
    python tools/gen_param_aliases.py --source PATH [--check]

``--source`` points at an s-dftd3 checkout. ``--check`` verifies the
committed ``aliases.toml`` is up to date instead of overwriting it (exit 1
on mismatch).
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

try:
    import tomllib  # pyright: ignore[reportMissingImports]
except ModuleNotFoundError:  # pragma: no cover
    import tomli as tomllib  # type: ignore[no-redef]

HERE = Path(__file__).resolve().parent
PARAM_TOML = HERE.parent / "src" / "tad_dftd3" / "param" / "parameters.toml"
ALIASES_TOML = HERE.parent / "src" / "tad_dftd3" / "param" / "aliases.toml"

CASE_ARM_RE = re.compile(r"case\(([^)]*)\)\s*;\s*id\s*=\s*(\w+)")
LITERAL_RE = re.compile(r'"([^"]*)"')

# Functionals that s-dftd3's Fortran `get_method_id` knows about but that have
# no entry in the shipped `parameters.toml` at all -- these cannot resolve to
# any canonical key regardless of normalization, and are expected to remain
# unresolved. If upstream ever adds TOML data for one of these, re-running
# this script will pick it up automatically and this list should shrink.
KNOWN_MISSING_TOML_ENTRY = {
    "b3lypg",
    "b3lyp3",
    "b86bpbe",
    "b86bpbe0",
    "dm21",
    "dm21m",
    "dm21mc",
    "dm21mu",
    "m06hf",
    "pbe38",
    "slaterdiracexchange",
}


def _norm_input(s: str) -> str:
    """Fortran's own runtime normalization of a user-supplied method name."""
    return s.lower().replace("-", "")


def _norm_match(s: str) -> str:
    """Richer normalization used only to bridge Fortran literal spelling to
    TOML table-key spelling while *generating* the alias table."""
    s = s.lower()
    for ch in "-_/":
        s = s.replace(ch, "")
    return s


def extract_case_arms(param_f90: Path) -> list[list[str]]:
    text = param_f90.read_text(encoding="utf-8")
    m = re.search(
        r"function get_method_id\(method\).*?end function get_method_id",
        text,
        re.S,
    )
    if not m:
        raise RuntimeError(f"could not find get_method_id in {param_f90}")

    groups = []
    for literals, enum_id in CASE_ARM_RE.findall(m.group(0)):
        if enum_id == "p_invalid":
            continue
        groups.append(LITERAL_RE.findall(literals))
    return groups


def build_alias_map(
    groups: list[list[str]], canonical_keys: set[str]
) -> tuple[dict[str, str], list[str]]:
    normed_canonical = {_norm_match(k): k for k in canonical_keys}

    alias_map: dict[str, str] = {}
    unresolved: list[str] = []

    for aliases in groups:
        direct = {
            a: normed_canonical[_norm_match(a)]
            for a in aliases
            if _norm_match(a) in normed_canonical
        }
        if direct:
            targets = set(direct.values())
            for a in aliases:
                if a in direct:
                    alias_map[_norm_input(a)] = direct[a]
                elif len(targets) == 1:
                    alias_map[_norm_input(a)] = next(iter(targets))
                else:
                    unresolved.append(a)
        else:
            unresolved.extend(aliases)

    return alias_map, unresolved


def render_toml(alias_map: dict[str, str]) -> str:
    lines = [
        "# Generated by tools/gen_param_aliases.py from s-dftd3's",
        "# src/dftd3/param.f90 (function get_method_id). Do not hand-edit;",
        "# re-run the script when upstream aliasing changes.",
        "[alias]",
    ]
    for alias in sorted(alias_map):
        canonical = alias_map[alias]
        if alias == canonical:
            continue
        lines.append(f"{_toml_key(alias)} = {_toml_key(canonical)}")
    lines.append("")
    return "\n".join(lines)


def _toml_key(s: str) -> str:
    escaped = s.replace("\\", "\\\\").replace('"', '\\"')
    return f'"{escaped}"'


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--source",
        type=Path,
        required=True,
        help="path to an s-dftd3 checkout",
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="verify aliases.toml is up to date instead of writing it",
    )
    args = parser.parse_args()

    param_f90 = args.source / "src" / "dftd3" / "param.f90"
    if not param_f90.exists():
        parser.error(
            f"cannot find {param_f90} (pass --source to an s-dftd3 checkout)"
        )

    with open(PARAM_TOML, "rb") as fh:
        canonical_keys = set(tomllib.load(fh)["parameter"].keys())

    groups = extract_case_arms(param_f90)
    alias_map, unresolved = build_alias_map(groups, canonical_keys)

    unresolved_set = set(unresolved)
    unexpected = unresolved_set - KNOWN_MISSING_TOML_ENTRY
    if unexpected:
        print(
            "gen_param_aliases: new unresolved aliases found that are not in "
            "KNOWN_MISSING_TOML_ENTRY -- inspect and either add TOML data "
            "upstream or extend the exception list:\n  "
            + "\n  ".join(sorted(unexpected)),
            file=sys.stderr,
        )
        return 1

    rendered = render_toml(alias_map)
    n_nontrivial = sum(1 for a, c in alias_map.items() if a != c)

    if args.check:
        current = (
            ALIASES_TOML.read_text(encoding="utf-8")
            if ALIASES_TOML.exists()
            else ""
        )
        if current != rendered:
            print(
                f"{ALIASES_TOML} is out of date; re-run without --check",
                file=sys.stderr,
            )
            return 1
        print(
            f"{ALIASES_TOML} is up to date ({n_nontrivial} non-trivial aliases)."
        )
        return 0

    ALIASES_TOML.write_text(rendered, encoding="utf-8")
    print(f"wrote {ALIASES_TOML} ({n_nontrivial} non-trivial aliases).")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
